### ISSUE TITLE
Release to PyPi

### ISSUE THREAD

**Issue by orokusaki** [Zopieux/py-gfm#1]
I noticed the latest release wasn't yet in [PyPi](https://pypi.python.org/pypi/py-gfm), yet.

If you need to request a transfer of ownership on PyPi, since the [original repo](https://github.com/dart-lang/py-gfm) unmaintained, you can make a request at (unfortunately) [SourceForge](https://sourceforge.net/projects/pypi/).

**Comment by Zopieux** [comment]
PyPi package ownership was part of the maintainership transfer to me. Before releasing to PyPi I wanted to revamp the test framework, but given I have no time to do that right now, I guess I'll upload  a new release soon. Thanks for your interest @orokusaki.

**Comment by Zopieux** [comment]
I took the time to write the missing tests for a 100% coverage, cleaned up the CI configuration and updated `setup.py`.

@orokusaki Release [0.1.2](/Zopieux/py-gfm/releases/tag/0.1.2) was uploaded to PyPi, along with a universal wheel.

**Comment by orokusaki** [comment]
@Zopieux awesome; 100% coverage is really great, and thanks for the PyPi release!!
