### ISSUE TITLE
AttributeError: module 'markdown.inlinepatterns' has no attribute 'BRK'

### ISSUE THREAD

**Issue by agathver** [Zopieux/py-gfm#13]
```
Markdown==3.0
py-gfm==0.1.3
```

Python 3.6.6

Here is a sample code that causes the error

```py
# imports ...
index_md = "# Hello World"
md = markdown.Markdown(extensions=[PartialGithubFlavoredMarkdownExtension()])
md.convert(index_md.read)
```

**Comment by fdevaux** [comment]
I just hit the same issue. FWIW it seems to be caused by the recent update of the markdown package to 3.0.0. As a workaround you can pin it to the previous version (`markdown==2.6.11`)

**Comment by Zopieux** [comment]
Thanks for your report. Markdown 3.0.0 being a major release, most internal code have changed, making dependent code (including py-gfm) broken. I'll pin `<3.0` in the dependencies before releasing a fix. Feel free to contribute a PR if you want a quicker release.

**Comment by Zopieux** [comment]
py-gfm 0.1.4 was pushed and released to PyPi.

**Comment by brunobord** [comment]
Hello @Zopieux: did you find some time to work on unpin the Markdown requirement? Do you know what precisely introduced this incompatibility?

**Comment by ignatenkobrain** [comment]
@Zopieux ping

**Comment by lsuttle** [comment]
Looks like there's a couple months old PR that resolves this issue, any chance that can be reviewed?

**Comment by shua** [comment]
Can we reopen this? I am seeing this issue with mkdocs (markdown >3.0) and latest py-gfm
