### ISSUE TITLE
Render task list without bullets

### ISSUE THREAD

**Issue by Crocmagnon** [Zopieux/py-gfm#2]
GitHub renders task lists without bullets :

- [ ] Hello
- [x] World

Currently, this implementation still shows the bullets.

Inspecting their code, they solved it by adding some classes to the enclosing `<ul>` and the inner `<li>` tags to remove the bullets.

**Comment by Crocmagnon** [comment]
I think I've worked my way around by adding some class to the `<li>` following the configuration described here : https://py-gfm.readthedocs.io/en/latest/lib/tasklist.html.

Though, it would be cool to be able to custom the enclosing `<ul>` too !

**Comment by Zopieux** [comment]
`py-gfm` provides no default CSS as it is only a Markdown parser. Nevertheless, I do agree it would be useful to be able to add a list-level class (that is, on the `<ul>` or `<ol>`) so you don't have to mess with `item_attrs`.

Opening #3 to that end.

**Comment by Zopieux** [comment]
@Crocmagnon Implemented! See [the new section](https://py-gfm.readthedocs.io/en/latest/lib/tasklist.html#list-attributes) for your use case.
