### ISSUE TITLE
Missing LICENSE file in pypi package

### ISSUE THREAD

**Issue by Germano0** [Zopieux/py-gfm#5]
Hi, I am Germano from Fedora community. I am going to package py-gfm and include it into Fedora repositories. We found out that the LICENSE file is missing in pypi package file 0.1.3

Have a nice day

**Comment by Zopieux** [comment]
Guess I have to add it to some `MANIFEST`. I'll look into it after my holidays. Thanks for the report.

**Comment by Zopieux** [comment]
I will not create a new release just for this change. Feel free to build your own distributions with the change! Thanks for your packaging work @Germano0.
