### ISSUE TITLE
problem with "one-column tables"

### ISSUE THREAD

**Issue by brunobord** [Zopieux/py-gfm#8]
Hello,

Here's the following markdown:

```markdown
| Header         |
| -------------- |
| Column content |
```

It's rendered as follows on github:

| Header         |
| -------------- |
| Column content |

But when it's parsed and rendered using py-gfm, it's rendered like this:

```
| Header         |
| -------------- |
| Column content |
```

Could you please fix that in a next release?

**Comment by brunobord** [comment]
looks like it's a Python-Markdown issue... https://github.com/waylan/Python-Markdown/issues/539

**Comment by brunobord** [comment]
It's fixed here, so I'll wait for the next release. sorry for the noise.

**Comment by Zopieux** [comment]
No problem, thanks for reporting anyway.
