### ISSUE TITLE
Way to disable specific features?

### ISSUE THREAD

**Issue by rhyst** [Zopieux/py-gfm#9]
Is there a way to disable for example "Literal line breaks"?

**Comment by Zopieux** [comment]
@rhyst Just create your own instance of Markdown with the full list of extensions you want to include, instead of the big `GithubFlavoredMarkdownExtension` one that gathers the others.

There is [a dedicated section](https://py-gfm.readthedocs.io/en/latest/#a-la-carte) for that in the docs.

**Comment by rhyst** [comment]
Ah, thanks. I was confused because there doesn't seem to be an extension for the literal line breaks.

**Comment by tomjaguarpaw** [comment]
I'm confused too.  What do you have to omit to disable literal line breaks?

**Comment by tomjaguarpaw** [comment]
It seems to be this that converts new line to line breaks: https://github.com/Zopieux/py-gfm/blob/cf931b47031b68e34fd5c88e6da28fabe179adb4/mdx_gfm/__init__.py#L54

"Nl2Br" presumably stands for "new line to line break".

**Comment by tomjaguarpaw** [comment]
To be specific, the way you get GitHub flavoured Markdown with py-gfm to omit hard line breaks is

    markdown.Markdown(extensions=[PartialGithubFlavoredMarkdownExtension()])
